spring:
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, prometheus, logfile
      base-path: /api/actuator
  endpoint:
    info:
      enabled: true
    prometheus:
      enabled: true
    logfile:
      enabled: true
      external-file: ${logging.file.path}
    health:
      enabled: true
      defaults:
        enabled: false
      show-details: when_authorized
      time-to-live: 60s
      jms:
        enabled: true
      diskspace:
        enabled: true
      mongo:
        enabled: true
      mail:
        enabled: true
      redis:
        enabled: true
      status:
        http-mapping:
          UP: 200
          UNKNOWN: 200
          DOWN: 200
          OUT_OF_SERVICE: 200
