spring:
  artemis:
    broker-url: ${ARTEMIS_URL:tcp://localhost:61616}
    user: ${ARTEMIS_USER:root}
    password: ${ARTEMIS_PASSWORD:root}
#    embedded:
#      persistent: true
#      data-directory: ${application.basePath}/artemis