spring:
  data:
    mongodb:
      host: ${MONGO_DB_HOST:localhost}
      port: ${MONGO_DB_PORT:27018}
      username: ${MONGO_DB_USERNAME:root}
      password: ${MONGO_DB_PASSWORD:root}
      database: ${MONGO_DB_DATABASE_NAME:artcoded}
      authentication-database: ${MONGO_DB_AUTH_DB:admin}