application:
  upload:
    defaultGraph: ${DEFAULT_GRAPH_UPLOAD:https://bittich.be/graphs/public}
    pathToBackup: ${application.basePath}/files-backup
    pathToUpload: ${application.basePath}/files
    peppolFTP: ${PEPPOL_FTP_URI:sftp://sftp:22}
    expenseIdempotentFilePath: ${application.basePath}/peppol_expense
    successInvoiceIdempotentFilePath: ${application.basePath}/peppol_invoice
    peppolFTPUser: ${PEPPOL_FTP_USER:peppol}
    peppolFTPHostKey: ${PEPPOL_FTP_HOST_KEY:/peppol/id_rsa}
  cv:
    defaultGraph: ${DEFAULT_GRAPH_CV:https://bittich.be/graphs/public}
  dossier:
    pathToBackup: ${application.basePath}/dossiers-backup
  script:
    pathToScripts: ${PATH_TO_SCRIPTS:classpath:scripts}
  mongo:
    pathToDump: ${application.basePath}/dump
    pathToDumpSnapshot: ${application.basePath}/dump-snapshot
  fixture:
    cv: false
  admin:
    email: ${ADMIN_EMAIL:noreply@somehost.com}
spring:
  # threads:
  #   virtual:
  #     enabled: true
  config:
    import:
      - classpath:config/web.yml
      - classpath:config/cache.yml
      - classpath:config/mongodb.yml
      - classpath:config/logging.yml
      - classpath:config/security.yml
      - classpath:config/mail.yml
      - classpath:config/actuator.yml
      - classpath:config/yahoo.yml
      - ${MAIL_SEARCH_TERM:classpath:config/search-term.yml}
  application:
    name: artcoded-backend-${spring.profiles.active}
  profiles:
    active: ${PROFILE_ACTIVE:dev}
camel:
  # doesn't seemt to do anything, as always with camel docs
  # threads:
  #   virtual:
  #     enabled: ${CAMEL_VIRTUAL_THREADS_ENABLED:true}
  springboot:
    name: camel-${spring.application.name}

mongock:
  migration-scan-package:
    - tech.artcoded.websitev2.changelogs
  transactional: ${MONGO_TRANSACTION_ENABLED:false}
  enabled: ${MONGOCK_ENABLED:true}
