application:
  upload:
    defaultGraph: ${DEFAULT_GRAPH_UPLOAD:https://bittich.be/graphs/public}
    pathToBackup: ${application.basePath}/files-backup
    pathToUpload: ${application.basePath}/files
  cv:
    defaultGraph: ${DEFAULT_GRAPH_CV:https://bittich.be/graphs/public}
  dossier:
    pathToBackup: ${application.basePath}/dossiers-backup
  mongo:
    pathToDump: ${application.basePath}/dump
  fixture:
    cv: false
spring:
  config:
    import:
      - classpath:config/web.yml
      - classpath:config/cache.yml
      - classpath:config/mongodb.yml
      - classpath:config/logging.yml
      - classpath:config/security.yml
      - classpath:config/mail.yml
      - classpath:config/actuator.yml
      - classpath:config/yahoo.yml
      - ${MAIL_SEARCH_TERM:classpath:config/search-term.yml}
  application:
    name: artcoded-backend-${spring.profiles.active}
  profiles:
    active: ${PROFILE_ACTIVE:dev}
camel:
  springboot:
    name: camel-${spring.application.name}

mongock:
  migration-scan-package:
    - tech.artcoded.websitev2.changelogs
  transaction-enabled: ${MONGOCK_TRANSACTION_ENABLED:false}
  enabled: ${MONGOCK_ENABLED:true}
